version: '3.8'
services:
    nginx-proxy:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        networks:
            - coffeekraken
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt

networks:
    coffeekraken:
        name: coffeekraken
        external: true
