export default {
    extends: 'themeBase',

    colorStates: {
        text: '--darken 0',
        placeholder: '--lighten 40',
        surface: '--lighten 49',
        foreground: '--lighten 50',
        background: '--darken 40',
        border: '--lighten 45',
        dark: '--darken 45',
        light: '--lighten 45',
        gradientStart: '--lighten 0',
        gradientEnd: '--darken 20',
        ':hover': {
          text: '--darken 0',
          placeholder: '--lighten 40',
          surface: '--lighten 49',
          foreground: '--lighten 50',
          background: '--darken 40',
          border: '--lighten 40',
          dark: '--darken 45',
          light: '--lighten 45',
        },
        ':focus': {
          text: '--darken 0',
          placeholder: '--lighten 40',
          surface: '--lighten 49',
          foreground: '--lighten 50',
          background: '--darken 40',
          border: '--lighten 40',
          dark: '--darken 45',
          light: '--lighten 45',
        },
        ':active': {
          text: '--darken 0',
          placeholder: '--lighten 40',
          surface: '--lighten 49',
          foreground: '--lighten 50',
          background: '--darken 40',
          border: '--lighten 40',
          dark: '--darken 45',
          light: '--lighten 45',
        },
        ':highlight': {
          text: '--darken 0',
          placeholder: '--lighten 40',
          surface: '--lighten 49',
          foreground: '--lighten 50',
          background: '--darken 40',
          border: '--lighten 40',
          dark: '--darken 45',
          light: '--lighten 45',
        }
  }
}