export default {
    extends: 'themeBase',

    colorStates: {
        text: '--darken 0',
        placeholder: '--alpha 0.4',
        foreground: '--lighten 50',
        surface: '--lighten 49',
        surfaceForeground: '--darken 0',
        background: '--lighten 47',
        backgroundForeground: '--darken 0',
        border: '--alpha 0.1',
        dark: '--darken 45',
        light: '--lighten 45',
        gradientStart: '--lighten 0',
        gradientEnd: '--darken 20',
        ':hover': {
          text: '--darken 0',
          placeholder: '--alpha 0.5',
          surface: '--lighten 47',
          surfaceForeground: '--darken 0',
          foreground: '--lighten 50',
          background: '--darken 40',
          backgroundForeground: '--darken 0',
          border: '--alpha 0.2',
          dark: '--darken 45',
          light: '--lighten 45',
        },
        ':focus': {
          text: '--darken 0',
          placeholder: '--alpha 0.6',
          surface: '--lighten 43',
          surfaceForeground: '--darken 0',
          foreground: '--lighten 50',
          background: '--darken 40',
          backgroundForeground: '--darken 0',
          border: '--alpha 0.3',
          dark: '--darken 45',
          light: '--lighten 45',
        },
        ':active': {
          text: '--darken 0',
          placeholder: '--alpha 0.6',
          surface: '--lighten 43',
          surfaceForeground: '--darken 0',
          foreground: '--lighten 50',
          background: '--darken 40',
          backgroundForeground: '--darken 0',
          border: '--alpha 0.3',
          dark: '--darken 45',
          light: '--lighten 45',
        }
  }
}