export default {
    extends: 'themeBase',

    colorStates: {
        '0': '--darken 50',
        '5': '--darken 45',
        '10': '--darken 40',
        '15': '--darken 35',
        '20': '--darken 30',
        '25': '--darken 25',
        '30': '--darken 20',
        '35': '--darken 15',
        '40': '--darken 10',
        '45': '--darken 5',
        '50': '--darken 0',
        '55': '--lighten 5',
        '60': '--lighten 10',
        '65': '--lighten 15',
        '70': '--lighten 20',
        '75': '--lighten 25',
        '80': '--lighten 30',
        '85': '--lighten 35',
        '90': '--lighten 40',
        '95': '--lighten 48',
        '100': '--lighten 50',

        text: '[theme.colorStates.50]',
        foreground: '--lighten 50',
        background: '--lighten 50',
        backgroundForeground: '--darken 0',
        surface: '--lighten 47',
        surfaceForeground: '--darken 0',
        border: '--alpha 0.2',
        gradientStart: '--lighten 0',
        gradientEnd: '--darken 20',
        
        ':hover': {
          '0': '--darken 55',
          '5': '--darken 50',
          '10': '--darken 45',
          '15': '--darken 40',
          '20': '--darken 35',
          '25': '--darken 30',
          '30': '--darken 25',
          '35': '--darken 20',
          '40': '--darken 15',
          '45': '--darken 10',
          '50': '--darken 5',
          '55': '--lighten 0',
          '60': '--lighten 5',
          '65': '--lighten 10',
          '70': '--lighten 15',
          '75': '--lighten 20',
          '80': '--lighten 25',
          '85': '--lighten 30',
          '90': '--lighten 35',
          '95': '--lighten 40',
          '100': '--lighten 45',
          text: '[theme.colorStates.50]',
          foreground: '--lighten 50',
          background: '--lighten 50',
          backgroundForeground: '--darken 0',
          surface: '--lighten 45',
          surfaceForeground: '--darken 0',
          border: '--alpha 0.3',
          gradientStart: '--lighten 0',
          gradientEnd: '--darken 20',
        },
        ':focus': {
          '0': '--darken 60',
          '5': '--darken 55',
          '10': '--darken 50',
          '15': '--darken 45',
          '20': '--darken 40',
          '25': '--darken 35',
          '30': '--darken 30',
          '35': '--darken 25',
          '40': '--darken 20',
          '45': '--darken 15',
          '50': '--darken 10',
          '55': '--darken 5',
          '60': '--lighten 0',
          '65': '--lighten 5',
          '70': '--lighten 10',
          '75': '--lighten 15',
          '80': '--lighten 20',
          '85': '--lighten 25',
          '90': '--lighten 30',
          '95': '--lighten 35',
          '100': '--lighten 40',
          text: '--darken 0',
          surface: '--lighten 46'
        },
        ':active': {
          '0': '--darken 60',
          '10': '--darken 50',
          '20': '--darken 40',
          '30': '--darken 30',
          '40': '--darken 20',
          '50': '--darken 10',
          '60': '--lighten 0',
          '70': '--lighten 10',
          '80': '--lighten 20',
          '90': '--lighten 30',
          '100': '--lighten 40',
          text: '--darken 0',
          surface: '--lighten 46'
        }
  }
}