// @ts-nocheck

import __deepMerge from '../../object/deepMerge';
import __tmpDir from '../../fs/tmpDir';
import __fs from 'fs';
import __ensureDirSync from '../../fs/ensureDirSync';
import __removeSync from '../../fs/removeSync';
import __sugarConfig from '../../config/sugar';
import __toString from '../../string/toString';
import __SCacheAdapter from './SCacheAdapter';

/**
 * @name                                SCacheFsAdapter
 * @namespace           sugar.node.fs.cacheAdapters
 * @type                                Class
 * @beta
 *
 * A filesystem SCache adapter that allows you to store your cache items on the user system
 *
 * @example             js
 * const cache = new SCache({
 *    ttl: 100,
 *    adapter: new SCacheFsAdapter({
 *      rootDir: '/my/cool/folder
 *    })
 * });
 *
 * @todo      interface
 * @todo      doc
 * @todo      tests
 *
 * @since         2.0.0
 * @author         Olivier Bossel <olivier.bossel@gmail.com> (https://olivierbossel.com)
 */
export = class SCacheFsAdapter extends __SCacheAdapter {
  /**
   * @name                              constructor
   * @type                              Function
   *
   * Construct the SCacheFsAdapter instance with the settings passed in object format. See description bellow.
   *
   * @param         {Object}          [settings={}]             An object to configure the SCacheFsAdapter instance. This is specific to each adapters.settings.settings...
   * - rootDir (config.storage.cacheDir) {String}: Specify the root directory where to put all the files to cache
   *
   * @author         Olivier Bossel <olivier.bossel@gmail.com> (https://olivierbossel.com)
   */
  constructor(cache, settings = {}) {
    super(
      cache,
      __deepMerge(
        {
          rootDir: __sugarConfig('storage.cacheDir') || `${__tmpDir()}/SCache`
        },
        settings
      )
    );
  }

  /**
   * @name                          set
   * @type                          Function
   *
   * Set a cache item on the filesystem
   *
   * @param             {String}              name              The item name
   * @param             {Mixed}               value             The value to save
   * @param             {Object}              [settings={}]     A settings object to override the default ones defined on the SCache instance
   * @return            {Object|Boolean}                        Return the objectToSave generated by the "this.processItem" method, or false if something goes wrong...
   *
   * @example           js
   * await myCache.set('myCoolItem', { hello: 'world' }, {
   *    ttl: 40000
   * });
   *
   * @author         Olivier Bossel <olivier.bossel@gmail.com> (https://olivierbossel.com)
   */
  async set(name, value) {
    // generate the item fs name
    const fsName = `${this.cache.name}/${name}.json`.replace(/\/\//gm, '/');

    // ensure we have the folder
    __ensureDirSync(
      `${this._settings.rootDir}/${fsName.split('/').slice(0, -1).join('/')}`
    );

    // write the json file
    __fs.writeFileSync(`${this._settings.rootDir}/${fsName}`, value);
    // write has been done correctly
    return true;
  }

  /**
   * @name                          get
   * @type                          Function
   *
   * Get a cache item on the filesystem
   *
   * @param             {String}              name              The item name
   * @return            {Object|Boolean}                        Return the objectToSave generated by the "this.processItem" method, or false if something goes wrong...
   *
   * @example           js
   * await myCache.get('myCoolItem');
   *
   * @author         Olivier Bossel <olivier.bossel@gmail.com> (https://olivierbossel.com)
   */
  async get(name) {
    // generate the item fs name
    if (name.slice(0, 1) === '/') name = name.slice(1);
    const fsName = `${this.cache.name}/${name}.json`;
    // check that the file exists
    if (!__fs.existsSync(`${this._settings.rootDir}/${fsName}`)) return null;
    // read the json file
    return __fs.readFileSync(`${this._settings.rootDir}/${fsName}`, 'utf8');
  }

  /**
   * @name                          delete
   * @type                          Function
   *
   * Delete a cache item on the filesystem
   *
   * @param             {String}              name              The item name
   * @return            {Boolean}                               true if all of, false if not...
   *
   * @example           js
   * await myCache.delete('myCoolItem');
   *
   * @author         Olivier Bossel <olivier.bossel@gmail.com> (https://olivierbossel.com)
   */
  async delete(name) {
    // generate the item fs name
    const fsName = `${this.cache.name}/${name}.json`;
    // read the json file
    return __fs.unlinkSync(`${this._settings.rootDir}/${fsName}`);
  }

  /**
   * @name                          clear
   * @type                          Function
   *
   * Clear all the items in the current cache
   *
   * @return            {Boolean}                               true if all of, false if not...
   *
   * @example           js
   * await myCache.clear;
   *
   * @author         Olivier Bossel <olivier.bossel@gmail.com> (https://olivierbossel.com)
   */
  async clear() {
    // read the json file
    return __removeSync(`${this._settings.rootDir}/${this.cache.name}`);
  }
};
