/* SHighlightJs.svelte generated by Svelte v3.37.0 */
import {
	SvelteElement,
	add_location,
	append_dev,
	attribute_to_object,
	detach_dev,
	dispatch_dev,
	element,
	globals,
	init,
	insert_dev,
	noop,
	safe_not_equal,
	validate_slots
} from "svelte/internal";

const { Object: Object_1, console: console_1 } = globals;
const file = "SHighlightJs.svelte";

function create_fragment(ctx) {
	let div;
	let h1;

	const block = {
		c: function create() {
			div = element("div");
			h1 = element("h1");
			h1.textContent = "Hello worlc";
			this.c = noop;
			add_location(h1, file, 47, 1, 1605);
			add_location(div, file, 46, 0, 1598);
		},
		l: function claim(nodes) {
			throw new Error("options.hydrate only works if the component was compiled with the `hydratable: true` option");
		},
		m: function mount(target, anchor) {
			insert_dev(target, div, anchor);
			append_dev(div, h1);
		},
		p: noop,
		i: noop,
		o: noop,
		d: function destroy(detaching) {
			if (detaching) detach_dev(div);
		}
	};

	dispatch_dev("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	validate_slots("s-highlight-js", slots, []);
	"use strict";

	var __extends = this && this.__extends || (function () {
		var extendStatics = function (d, b) {
			extendStatics = Object.setPrototypeOf || { __proto__: [] } instanceof Array && function (d, b) {
				d.__proto__ = b;
			} || function (d, b) {
				for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
			};

			return extendStatics(d, b);
		};

		return function (d, b) {
			extendStatics(d, b);

			function __() {
				this.constructor = d;
			}

			d.prototype = b === null
			? Object.create(b)
			: (__.prototype = b.prototype, new __());
		};
	})();

	var __importDefault = this && this.__importDefault || function (mod) {
		return mod && mod.__esModule ? mod : { "default": mod };
	};

	Object.defineProperty(exports, "__esModule", { value: true });
	var highlight_js_1 = __importDefault(require("highlight.js"));
	var javascript_1 = __importDefault(require("highlight.js/lib/languages/javascript"));
	highlight_js_1.default.registerLanguage("javascript", javascript_1.default);
	var SSvelteComponent_1 = __importDefault(require("@coffeekraken/sugar/js/svelte/SSvelteComponent"));

	var MyCoolComponent = /** @class */ (function (_super) {
		__extends(MyCoolComponent, _super);

		function MyCoolComponent() {
			return _super.call(this, { svelteComponent: {} }) || this;
		}

		return MyCoolComponent;
	})(SSvelteComponent_1.default);

	console.log("Plfffffp");
	new MyCoolComponent();
	const writable_props = [];

	Object_1.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<s-highlight-js> was created with unknown prop '${key}'`);
	});

	$$self.$capture_state = () => ({
		__extends,
		__importDefault,
		highlight_js_1,
		javascript_1,
		SSvelteComponent_1,
		MyCoolComponent
	});

	$$self.$inject_state = $$props => {
		if ("__extends" in $$props) __extends = $$props.__extends;
		if ("__importDefault" in $$props) __importDefault = $$props.__importDefault;
		if ("highlight_js_1" in $$props) highlight_js_1 = $$props.highlight_js_1;
		if ("javascript_1" in $$props) javascript_1 = $$props.javascript_1;
		if ("SSvelteComponent_1" in $$props) SSvelteComponent_1 = $$props.SSvelteComponent_1;
		if ("MyCoolComponent" in $$props) MyCoolComponent = $$props.MyCoolComponent;
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [];
}

class SHighlightJs extends SvelteElement {
	constructor(options) {
		super();
		this.shadowRoot.innerHTML = `<style>h1{color:blue;background:red}</style>`;

		init(
			this,
			{
				target: this.shadowRoot,
				props: attribute_to_object(this.attributes),
				customElement: true
			},
			instance,
			create_fragment,
			safe_not_equal,
			{}
		);

		if (options) {
			if (options.target) {
				insert_dev(options.target, this, options.anchor);
			}
		}
	}
}

customElements.define("s-highlight-js", SHighlightJs);
export default SHighlightJs;