"use strict";
// @shared
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
const _SType_1 = __importDefault(require("./_SType"));
const stringTypeDescriptor_1 = __importDefault(require("./descriptors/stringTypeDescriptor"));
const mapTypeDescriptor_1 = __importDefault(require("./descriptors/mapTypeDescriptor"));
const objectTypeDescriptor_1 = __importDefault(require("./descriptors/objectTypeDescriptor"));
const arrayTypeDescriptor_1 = __importDefault(require("./descriptors/arrayTypeDescriptor"));
const integerTypeDescriptor_1 = __importDefault(require("./descriptors/integerTypeDescriptor"));
const numberTypeDescriptor_1 = __importDefault(require("./descriptors/numberTypeDescriptor"));
const booleanTypeDescriptor_1 = __importDefault(require("./descriptors/booleanTypeDescriptor"));
const undefinedTypeDescriptor_1 = __importDefault(require("./descriptors/undefinedTypeDescriptor"));
const nullTypeDescriptor_1 = __importDefault(require("./descriptors/nullTypeDescriptor"));
const symbolTypeDescriptor_1 = __importDefault(require("./descriptors/symbolTypeDescriptor"));
const bigintTypeDescriptor_1 = __importDefault(require("./descriptors/bigintTypeDescriptor"));
const dateTypeDescriptor_1 = __importDefault(require("./descriptors/dateTypeDescriptor"));
const functionTypeDescriptor_1 = __importDefault(require("./descriptors/functionTypeDescriptor"));
const weakmapTypeDescriptor_1 = __importDefault(require("./descriptors/weakmapTypeDescriptor"));
const weaksetTypeDescriptor_1 = __importDefault(require("./descriptors/weaksetTypeDescriptor"));
const setTypeDescriptor_1 = __importDefault(require("./descriptors/setTypeDescriptor"));
const classTypeDescriptor_1 = __importDefault(require("./descriptors/classTypeDescriptor"));
_SType_1.default.registerType(stringTypeDescriptor_1.default);
_SType_1.default.registerType(mapTypeDescriptor_1.default);
_SType_1.default.registerType(objectTypeDescriptor_1.default);
_SType_1.default.registerType(arrayTypeDescriptor_1.default);
_SType_1.default.registerType(integerTypeDescriptor_1.default);
_SType_1.default.registerType(numberTypeDescriptor_1.default);
_SType_1.default.registerType(booleanTypeDescriptor_1.default);
_SType_1.default.registerType(undefinedTypeDescriptor_1.default);
_SType_1.default.registerType(nullTypeDescriptor_1.default);
_SType_1.default.registerType(symbolTypeDescriptor_1.default);
_SType_1.default.registerType(bigintTypeDescriptor_1.default);
_SType_1.default.registerType(dateTypeDescriptor_1.default);
_SType_1.default.registerType(functionTypeDescriptor_1.default);
_SType_1.default.registerType(weakmapTypeDescriptor_1.default);
_SType_1.default.registerType(weaksetTypeDescriptor_1.default);
_SType_1.default.registerType(setTypeDescriptor_1.default);
_SType_1.default.registerType(classTypeDescriptor_1.default);
module.exports = _SType_1.default;
//# sourceMappingURL=module.js.map