export default {
  slides: [`Something cool`, 'something else', 'wefwiefjowiejfiowefjoiwej'],
  lnf: 'default-contained',
  // ratio: '1',
  controls: true,
  pad: true,
  nav: true,
  progress: true,
  swipe: true,
  mousewheel: true,
  clickOnSlide: false,
  loop: true,
  direction: 'horizontal',
  container: true,
  uiContainer: false,
  behavior: 'scroll',
};
