/* component.svelte generated by Svelte v3.32.0 */
import {
	SvelteComponentDev,
	add_location,
	append_dev,
	attr_dev,
	detach_dev,
	dispatch_dev,
	element,
	globals,
	init,
	insert_dev,
	noop,
	safe_not_equal,
	validate_slots
} from "svelte/internal";

const { Object: Object_1, console: console_1 } = globals;
const file = "component.svelte";

function add_css() {
	var style = element("style");
	style.id = "svelte-aezs1y-style";
	style.textContent = "h1.svelte-aezs1y{color:#f2bc2b;background:red}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY29tcG9uZW50LnN2ZWx0ZSIsInNvdXJjZXMiOlsiY29tcG9uZW50LnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0IHR5cGU9XCJ0ZXh0L3RzXCI+dmFyIF9faW1wb3J0RGVmYXVsdCA9ICh0aGlzICYmIHRoaXMuX19pbXBvcnREZWZhdWx0KSB8fCBmdW5jdGlvbiAobW9kKSB7XG4gICAgcmV0dXJuIChtb2QgJiYgbW9kLl9fZXNNb2R1bGUpID8gbW9kIDogeyBcImRlZmF1bHRcIjogbW9kIH07XG59O1xuKGZ1bmN0aW9uIChmYWN0b3J5KSB7XG4gICAgaWYgKHR5cGVvZiBtb2R1bGUgPT09IFwib2JqZWN0XCIgJiYgdHlwZW9mIG1vZHVsZS5leHBvcnRzID09PSBcIm9iamVjdFwiKSB7XG4gICAgICAgIHZhciB2ID0gZmFjdG9yeShyZXF1aXJlLCBleHBvcnRzKTtcbiAgICAgICAgaWYgKHYgIT09IHVuZGVmaW5lZCkgbW9kdWxlLmV4cG9ydHMgPSB2O1xuICAgIH1cbiAgICBlbHNlIGlmICh0eXBlb2YgZGVmaW5lID09PSBcImZ1bmN0aW9uXCIgJiYgZGVmaW5lLmFtZCkge1xuICAgICAgICBkZWZpbmUoW1wicmVxdWlyZVwiLCBcImV4cG9ydHNcIiwgXCJAY29mZmVla3Jha2VuL3N1Z2FyL2pzL3N2ZWx0ZS9TU3ZlbHRlQ29tcG9uZW50XCJdLCBmYWN0b3J5KTtcbiAgICB9XG59KShmdW5jdGlvbiAocmVxdWlyZSwgZXhwb3J0cykge1xuICAgIFwidXNlIHN0cmljdFwiO1xuICAgIE9iamVjdC5kZWZpbmVQcm9wZXJ0eShleHBvcnRzLCBcIl9fZXNNb2R1bGVcIiwgeyB2YWx1ZTogdHJ1ZSB9KTtcbiAgICBjb25zdCBTU3ZlbHRlQ29tcG9uZW50XzEgPSBfX2ltcG9ydERlZmF1bHQocmVxdWlyZShcIkBjb2ZmZWVrcmFrZW4vc3VnYXIvanMvc3ZlbHRlL1NTdmVsdGVDb21wb25lbnRcIikpO1xuICAgIGNsYXNzIE15Q29vbENvbXBvbmVudCBleHRlbmRzIFNTdmVsdGVDb21wb25lbnRfMS5kZWZhdWx0IHtcbiAgICAgICAgY29uc3RydWN0b3IoKSB7XG4gICAgICAgICAgICBzdXBlcih7XG4gICAgICAgICAgICAgICAgc3ZlbHRlQ29tcG9uZW50OiB7fVxuICAgICAgICAgICAgfSk7XG4gICAgICAgICAgICBjb25zb2xlLmxvZygnQ09NXj0nKTtcbiAgICAgICAgfVxuICAgIH1cbiAgICBuZXcgTXlDb29sQ29tcG9uZW50KCk7XG59KTtcbjwvc2NyaXB0PlxuXG48c3R5bGUgdHlwZT1cInRleHQvc2Nzc1wiPmgxIHtcbiAgY29sb3I6ICNmMmJjMmI7XG4gIGJhY2tncm91bmQ6IHJlZDtcbn08L3N0eWxlPlxuXG48ZGl2PlxuXHQ8aDE+SGVsbG8gd29ybGM8L2gxPlxuPC9kaXY+Il0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQTJCd0IsRUFBRSxjQUFDLENBQUMsQUFDMUIsS0FBSyxDQUFFLE9BQU8sQ0FDZCxVQUFVLENBQUUsR0FBRyxBQUNqQixDQUFDIn0= */";
	append_dev(document.head, style);
}

function create_fragment(ctx) {
	let div;
	let h1;

	const block = {
		c: function create() {
			div = element("div");
			h1 = element("h1");
			h1.textContent = "Hello worlc";
			attr_dev(h1, "class", "svelte-aezs1y");
			add_location(h1, file, 33, 1, 1082);
			add_location(div, file, 32, 0, 1075);
		},
		l: function claim(nodes) {
			throw new Error("options.hydrate only works if the component was compiled with the `hydratable: true` option");
		},
		m: function mount(target, anchor) {
			insert_dev(target, div, anchor);
			append_dev(div, h1);
		},
		p: noop,
		i: noop,
		o: noop,
		d: function destroy(detaching) {
			if (detaching) detach_dev(div);
		}
	};

	dispatch_dev("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	validate_slots("Component", slots, []);

	var __importDefault = this && this.__importDefault || function (mod) {
		return mod && mod.__esModule ? mod : { "default": mod };
	};

	(function (factory) {
		if (typeof module === "object" && typeof module.exports === "object") {
			var v = factory(require, exports);
			if (v !== undefined) module.exports = v;
		} else if (typeof define === "function" && define.amd) {
			define(["require", "exports", "@coffeekraken/sugar/js/svelte/SSvelteComponent"], factory);
		}
	})(function (require, exports) {
		"use strict";
		Object.defineProperty(exports, "__esModule", { value: true });
		const SSvelteComponent_1 = __importDefault(require("@coffeekraken/sugar/js/svelte/SSvelteComponent"));

		class MyCoolComponent extends SSvelteComponent_1.default {
			constructor() {
				super({ svelteComponent: {} });
				console.log("COM^=");
			}
		}

		new MyCoolComponent();
	});

	const writable_props = [];

	Object_1.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<Component> was created with unknown prop '${key}'`);
	});

	$$self.$capture_state = () => ({ __importDefault });

	$$self.$inject_state = $$props => {
		if ("__importDefault" in $$props) __importDefault = $$props.__importDefault;
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [];
}

class Component extends SvelteComponentDev {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-aezs1y-style")) add_css();
		init(this, options, instance, create_fragment, safe_not_equal, {});

		dispatch_dev("SvelteRegisterComponent", {
			component: this,
			tagName: "Component",
			options,
			id: create_fragment.name
		});
	}
}

export default Component;